# Generated by Django 4.1 on 2022-12-04 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_customuser_avatar_alter_media_file_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='like',
        ),
        migrations.AddField(
            model_name='media',
            name='likes',
            field=models.ManyToManyField(related_name='media_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
