# Generated by Django 4.1 on 2022-12-26 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_artist_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
